# Generated by Django 3.2.8 on 2021-10-27 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=200, null=True)),
                ('kakao_id', models.CharField(max_length=200)),
                ('point', models.DecimalField(decimal_places=2, default=4560000, max_digits=10)),
                ('profile_image', models.URLField(max_length=500, null=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
