# Generated by Django 3.2.7 on 2021-10-25 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='airplanetaxes',
            old_name='reservation_id',
            new_name='reservation',
        ),
        migrations.AlterModelTable(
            name='reservation',
            table='reservations',
        ),
    ]
